### ISSUE TITLE
Amend sectors 

### ISSUE THREAD

**Issue by MandyCostello** [davetaz/EDSA#21]
Amend sectors to: (these can all be mapped to the Eurostat classifiers)

Agriculture
Mining
Manufacturing
Energy
Water and waste management
Construction
Wholesale and retail
Transport
Accommodation and food services
Media
Data and information systems
Finance and insurance services
Real Estate
Professional services
Scientific and market research
Business administration services
Tourism
Public administration and defence
Government and public sector 
Education
Human health and social work
Arts, recreation and entertainment
Consumer services

**Comment by davetaz** [comment]
This can be done by @MandyCostello in js/survey.js
